image: vakz/node-firefox-e2e-aws-eb:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - ls
    - npm install
    - npx webdriver-manager update
    - xvfb-run npx ng e2e

deploy:
  stage: deploy
  script:
    - npm install
    - npx ng build --prod
    - aws s3 rm s3://redditprofiler-frontend --recursive
    - aws s3 cp ./dist/redditprofiler-frontend s3://redditprofiler-frontend --recursive -acl public-read
