image: vakz/node-firefox-e2e-aws-eb:latest

stages:
  - build
  - test
#  - deploy

build:
  stage: build
  script:
    - npm install
    - npx ng build --prod

test:
  stage: test
  script:
    - ls
    - npm install
    - npx webdriver-manager update
    - xvfb-run npx ng e2e
