image: hortonworks/cloudbreak-web-e2e:latest

stages:
  - build
  - test
#  - deploy

build:
  stage: build
  script:
    - npm install
    - npx ng build --prod

test:
  stage: test
  script: npx ng e2e
